// WebMCP tools for datacentertraining.us.
//
// Registers read-only catalog tools with navigator.modelContext so browser AI
// agents can query the course catalog without scraping the page. Tool names,
// descriptions, and JSON schemas come from /.well-known/mcp.json (generated by
// scripts/build-site.js); this file only implements what each tool returns.
// Every tool reads the static JSON in /api/ - nothing here can enroll, pay,
// submit a form, or touch an account.
//
// The same engine runs in Node (scripts/build-site.js), where it produces the
// example outputs published in the manifest, so examples always match reality.
(function (root) {
  'use strict';

  var TOOL_DATA = {
    list_courses: ['courses', 'roles'],
    get_course: ['courses'],
    compare_bundles: ['bundles'],
    recommend_courses: ['roles', 'bundles', 'courses'],
    get_credential_info: ['credentials'],
    answer_faq: ['faq', 'courses'],
    list_resources: ['resources']
  };

  var STOPWORDS = ('a an and are as at be by can do does for from how i if in is it its me my of on or ' +
    'our should so that the their them there these this to was we what when where which who why will ' +
    'with you your course courses training data center').split(' ');

  function words(text) {
    return String(text || '').toLowerCase().replace(/[^a-z0-9.\/+ -]+/g, ' ').split(/[\s/-]+/)
      .filter(function (w) { return w && STOPWORDS.indexOf(w) === -1; });
  }

  function includesText(haystack, needle) {
    return String(haystack || '').toLowerCase().indexOf(String(needle || '').toLowerCase()) !== -1;
  }

  function summary(c) {
    return {
      id: c.id, title: c.title, url: c.url, track: c.track, category: c.category,
      course_type: c.course_type, duration_hours: c.duration_hours, price_usd: c.price_usd,
      standards: c.standards, summary: c.summary
    };
  }

  function slugFrom(input) {
    if (input.course_id) return String(input.course_id).trim().toLowerCase();
    if (input.url) {
      var m = String(input.url).match(/\/courses\/([a-z0-9-]+)\.html/);
      return m ? m[1] : '';
    }
    return '';
  }

  // Role keywords -> role id (roles.json). Scored so "HVAC facilities tech" beats "facilities".
  function matchRole(roles, text) {
    var t = ' ' + String(text || '').toLowerCase() + ' ';
    var best = null, bestScore = 0;
    roles.forEach(function (r) {
      var score = 0;
      if (t.indexOf(' ' + r.id + ' ') !== -1) score += 5;
      r.keywords.forEach(function (k) { if (t.indexOf(k) !== -1) score += k.length > 6 ? 2 : 1; });
      if (score > bestScore) { best = r; bestScore = score; }
    });
    return best;
  }

  var tools = {
    list_courses: function (input, d) {
      var list = d.courses.courses.slice();
      var notes = [];
      if (input.language && input.language !== 'en') {
        return { total_matching: 0, returned: 0, courses: [], notes: ['All courses are offered in English only.'] };
      }
      if (input.query) {
        var q = words(input.query);
        list = list.filter(function (c) {
          var hay = [c.title, c.summary, c.category, c.track, c.standards.join(' '), c.description].join(' ').toLowerCase();
          return q.every(function (w) { return hay.indexOf(w) !== -1; });
        });
      }
      if (input.track) list = list.filter(function (c) { return c.track === input.track; });
      if (input.category) list = list.filter(function (c) { return c.category === input.category; });
      if (input.course_type) list = list.filter(function (c) { return c.course_type === input.course_type; });
      if (input.standard) list = list.filter(function (c) { return includesText(c.standards.join(' '), input.standard); });
      if (input.bundle_id) list = list.filter(function (c) { return c.bundles.some(function (b) { return b.id === input.bundle_id; }); });
      if (input.role) {
        var role = d.roles.roles.filter(function (r) { return r.id === input.role; })[0];
        if (role) list = list.filter(function (c) { return c.track === role.track; });
      }
      if (typeof input.max_price_usd === 'number') list = list.filter(function (c) { return c.price_usd <= input.max_price_usd; });
      if (typeof input.max_duration_hours === 'number') list = list.filter(function (c) { return c.duration_hours <= input.max_duration_hours; });
      var sorters = {
        title: function (a, b) { return a.title.localeCompare(b.title); },
        price_asc: function (a, b) { return a.price_usd - b.price_usd || a.title.localeCompare(b.title); },
        price_desc: function (a, b) { return b.price_usd - a.price_usd || a.title.localeCompare(b.title); },
        duration_asc: function (a, b) { return a.duration_hours - b.duration_hours || a.title.localeCompare(b.title); },
        duration_desc: function (a, b) { return b.duration_hours - a.duration_hours || a.title.localeCompare(b.title); }
      };
      list.sort(sorters[input.sort] || sorters.title);
      var total = list.length;
      var limit = input.limit || 44;
      if (!total) notes.push('No course matched every filter. Remove a filter or call list_courses with no input to see the full catalog; do not suggest courses that are not listed.');
      return { total_matching: total, returned: Math.min(total, limit), courses: list.slice(0, limit).map(summary), notes: notes };
    },

    get_course: function (input, d) {
      var slug = slugFrom(input);
      var course = d.courses.courses.filter(function (c) { return c.id === slug; })[0];
      if (!course) {
        return {
          found: false,
          error: 'not_found',
          message: 'No course with that id or URL. Use list_courses to find valid course ids; do not guess a closest match.'
        };
      }
      var related = course.related_course_ids.map(function (id) {
        return summary(d.courses.courses.filter(function (c) { return c.id === id; })[0]);
      });
      return { found: true, course: course, related_courses: related };
    },

    compare_bundles: function (input, d) {
      var list = d.bundles.bundles;
      if (input.bundle_ids && input.bundle_ids.length) {
        list = list.filter(function (b) { return input.bundle_ids.indexOf(b.id) !== -1; });
      }
      return {
        bundles: list.map(function (b) {
          return {
            id: b.id, name: b.name, track: b.track, price_usd: b.price_usd, list_price_usd: b.list_price_usd,
            savings_usd: b.savings_usd, savings_percent: b.savings_percent, course_count: b.course_count,
            total_hours: b.total_hours, audience: b.audience, url: b.url, course_ids: b.course_ids
          };
        }),
        notes: ['Prices are per seat in USD before seat-count volume discounts (2+ seats), which apply at checkout.']
      };
    },

    recommend_courses: function (input, d) {
      var role = matchRole(d.roles.roles, [input.role, input.work_context].join(' '));
      var caveats = [
        'Training guidance only, not legal or compliance advice. Employers decide who is qualified for which duties at their site.',
        'A certificate of completion documents training; it is not a license or a certification issued by a standards body.'
      ];
      if (!role) {
        return {
          matched: false,
          message: 'The role did not match a documented role. Ask the user which of the listed roles is closest instead of guessing.',
          available_roles: d.roles.roles.map(function (r) { return { id: r.id, label: r.label }; }),
          caveats: caveats
        };
      }
      var bundle = d.bundles.bundles.filter(function (b) { return b.id === role.bundle_id; })[0];
      var courses = d.courses.courses.filter(function (c) { return c.track === role.track; });
      courses.sort(function (a, b) {
        if (a.course_type !== b.course_type) return a.course_type === 'comprehensive' ? -1 : 1;
        return b.duration_hours - a.duration_hours || a.title.localeCompare(b.title);
      });
      if (typeof input.budget_usd === 'number') {
        var spent = 0;
        courses = courses.filter(function (c) {
          if (spent + c.price_usd > input.budget_usd) return false;
          spent += c.price_usd;
          return true;
        });
        if (bundle && bundle.price_usd <= input.budget_usd) caveats.push('The full ' + bundle.name + ' fits this budget and costs less than buying its courses one by one.');
      }
      return {
        matched: true,
        role: { id: role.id, label: role.label },
        track: role.track,
        reason: role.description,
        recommended_bundle: bundle ? {
          id: bundle.id, name: bundle.name, price_usd: bundle.price_usd, list_price_usd: bundle.list_price_usd,
          savings_usd: bundle.savings_usd, course_count: bundle.course_count, total_hours: bundle.total_hours, url: bundle.url
        } : null,
        courses: courses.map(function (c, i) {
          var s = summary(c);
          s.rank = i + 1;
          s.reason = c.course_type === 'comprehensive'
            ? 'Core full-discipline program for this track.'
            : 'Focused specialization in the ' + role.track + '.';
          return s;
        }),
        caveats: caveats
      };
    },

    get_credential_info: function (input, d) {
      var topic = input.topic || 'all';
      var c = d.credentials;
      var out = { topic: topic, last_reviewed: c.last_reviewed, source_url: c.source_url };
      if (topic === 'all') {
        Object.keys(c.topics).forEach(function (k) { out[k] = c.topics[k]; });
      } else {
        out[topic] = c.topics[topic];
      }
      out.do_not_claim = c.do_not_claim;
      return out;
    },

    answer_faq: function (input, d) {
      var q = words(input.question);
      var pool = [];
      if (input.course_id) {
        var course = d.courses.courses.filter(function (c) { return c.id === input.course_id; })[0];
        if (course) course.faqs.forEach(function (f) { pool.push({ question: f.question, answer: f.answer, source_url: course.url, boost: 1 }); });
      }
      d.faq.faqs.forEach(function (f) { pool.push({ question: f.question, answer: f.answer, source_url: f.source_url, boost: 0 }); });
      var scored = pool.map(function (f) {
        var qw = words(f.question), aw = words(f.answer), score = 0;
        q.forEach(function (w) {
          if (qw.indexOf(w) !== -1) score += 3;
          else if (aw.indexOf(w) !== -1) score += 1;
        });
        return { f: f, score: score ? score + f.boost : 0 };
      }).filter(function (x) { return x.score >= 3; });
      scored.sort(function (a, b) { return b.score - a.score; });
      var matches = scored.slice(0, 3).map(function (x) {
        return { question: x.f.question, answer: x.f.answer, source_url: x.f.source_url };
      });
      return {
        answered: matches.length > 0,
        matches: matches,
        last_reviewed: d.faq.last_updated,
        support: matches.length
          ? 'Answers are quoted from published pages. For anything they do not cover, contact ' + d.faq.support.email + ' or ' + d.faq.support.phone + '.'
          : 'No published answer matches. Do not improvise one; refer the user to ' + d.faq.support.email + ' or ' + d.faq.support.phone + '.'
      };
    },

    list_resources: function (input, d) {
      var list = d.resources.resources;
      if (input.type) list = list.filter(function (r) { return r.type === input.type; });
      if (input.topic) {
        var t = words(input.topic);
        list = list.filter(function (r) {
          var hay = (r.title + ' ' + r.description + ' ' + r.topics.join(' ')).toLowerCase();
          return t.some(function (w) { return hay.indexOf(w) !== -1; });
        });
      }
      if (input.audience) {
        var a = String(input.audience).toLowerCase();
        list = list.filter(function (r) { return !r.audience.length || r.audience.some(function (x) { return a.indexOf(x) !== -1 || x.indexOf(a) !== -1; }); });
      }
      return { count: list.length, resources: list.slice(0, input.limit || 25) };
    }
  };

  function run(name, input, data) {
    if (!tools[name]) throw new Error('Unknown tool: ' + name);
    return tools[name](input || {}, data);
  }

  var api = { run: run, toolData: TOOL_DATA, names: Object.keys(tools) };
  if (typeof module !== 'undefined' && module.exports) {
    module.exports = api;
    return;
  }

  // ---- Browser: register with WebMCP ----
  var mc = root.navigator && root.navigator.modelContext;
  if (!mc) return;
  var cache = {};
  function load(file) {
    if (!cache[file]) {
      cache[file] = fetch('/api/' + file + '.json', { credentials: 'omit' }).then(function (r) {
        if (!r.ok) throw new Error('Could not load /api/' + file + '.json');
        return r.json();
      });
    }
    return cache[file];
  }

  fetch('/.well-known/mcp.json', { credentials: 'omit' }).then(function (r) { return r.json(); }).then(function (manifest) {
    var defs = manifest.tools.filter(function (t) { return tools[t.name]; }).map(function (t) {
      return {
        name: t.name,
        description: t.description,
        inputSchema: t.inputSchema,
        annotations: t.annotations,
        execute: function (input) {
          var files = TOOL_DATA[t.name];
          return Promise.all(files.map(load)).then(function (loaded) {
            var d = {};
            files.forEach(function (f, i) { d[f] = loaded[i]; });
            var result = run(t.name, input, d);
            return { content: [{ type: 'text', text: JSON.stringify(result) }], structuredContent: result };
          });
        }
      };
    });
    if (typeof mc.provideContext === 'function') {
      mc.provideContext({ tools: defs });
    } else if (typeof mc.registerTool === 'function') {
      defs.forEach(function (def) { mc.registerTool(def); });
    }
  }).catch(function () { /* discovery is best-effort; the page works without it */ });
})(typeof window !== 'undefined' ? window : this);
